### ISSUE TITLE
Misleading error message when searching for repos with no issues

### ISSUE THREAD

**Issue by rbstrachan** [akashnimare/git-issues#7]
If no issues are found when searching for a repository the search returns
> No open issue found for user/repo

However, if you then change the `user` or `repo` you are searching for, the error message automatically updates with the new `user` or `repo` you are searching for, which makes it seem as if your new query has no issues either. This is fixed after clicking the search button.

---

**Steps to reproduce:**

1. **Open** `https://akashnimare.github.io/git-issues`.
<br><div align="center"><img src="https://user-images.githubusercontent.com/8963519/36641609-61e88fde-1a2a-11e8-88fc-c89353b5cbc6.png"></img></div><br>

2. **Search for** `null/null`. **This will return the error message as above.**
<br><div align="center"><img src="https://user-images.githubusercontent.com/8963519/36641660-5b630f12-1a2b-11e8-80ff-963d9ab8441c.png"></img></div><br>

3. **Type** `sindresorhus/ama`. **For as long as you don't hit search, the error message that was generated for the last search has updated and now makes it seem that** `sindresorhus/ama` **has no issues, although this is not true.**
<br><div align="center"><img src="https://user-images.githubusercontent.com/8963519/36641671-a0d0e998-1a2b-11e8-9632-ccf170627722.png"></img></div><br>

4. **Hit search. The issues from** `sindresorhus/ama` **will populate.**
<br><div align="center"><img src="https://user-images.githubusercontent.com/8963519/36641679-c925f802-1a2b-11e8-88f9-cd6b7d1dcf85.png"></img></div><br>

**Comment by akashnimare** [comment]
@rbstrachan yeah, I can reproduce this. I'll look into it (I was quite away from this project but now back and ready to refactor 🚀 )

**Comment by akashnimare** [comment]
@rbstrachan fixed.
